name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or whichever branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Compile with Emscripten
        run: |
          emcc main.c -s USE_SDL=2 -s USE_WEBGL2=1 -o index.html

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./  # Path to the folder containing index.html and other files

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
